application: hange-them-high
version: 1
runtime: python
api_version: 1


handlers:
- url: .*
  script: main.py

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin
